spring.application.name=gtfs-data-pipeline
gtfs.realtime.url=https://api.stm.info/pub/od/gtfs-rt/ic/v2/vehiclePositions
gtfs.realtime.api-key=${STM_API_KEY}
mapbox.access.token=${MAPBOX_ACCESS_TOKEN}
gtfs.schedule.url=https://www.stm.info/sites/default/files/gtfs/gtfs_stm.zip

# Ensure Spring Boot listens on the Cloud Run PORT variable
server.port=${PORT:8080}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never